version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3808:3306
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: final_project
      
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '6379:6379'