"""Settings

Revision ID: 1885bc93f181
Revises: 2baf0327b478
Create Date: 2022-12-12 13:05:32.345296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1885bc93f181'
down_revision = '2baf0327b478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sunday_start', sa.Time(), nullable=True),
    sa.Column('sunday_end', sa.Time(), nullable=True),
    sa.Column('monday_start', sa.Time(), nullable=True),
    sa.Column('monday_end', sa.Time(), nullable=True),
    sa.Column('tuesday_start', sa.Time(), nullable=True),
    sa.Column('tuesday_end', sa.Time(), nullable=True),
    sa.Column('wednesday_start', sa.Time(), nullable=True),
    sa.Column('wednesday_end', sa.Time(), nullable=True),
    sa.Column('thursday_start', sa.Time(), nullable=True),
    sa.Column('thursday_end', sa.Time(), nullable=True),
    sa.Column('friday_start', sa.Time(), nullable=True),
    sa.Column('friday_end', sa.Time(), nullable=True),
    sa.Column('saturday_start', sa.Time(), nullable=True),
    sa.Column('saturday_end', sa.Time(), nullable=True),
    sa.Column('business_name', sa.String(length=80), nullable=True),
    sa.Column('system_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
